## Voila, new exception extending IOError
class MyException(IOError):
    pass